events {}

http {
    upstream backend_servers {
        server v-serve-backend.onrender.com:443;
        server v-serve-hosting-2.onrender.com:443;
        server volunteer-management-system-backend.onrender.com:443;
    }

    server {
        listen 80;

        location / {
            proxy_pass https://backend_servers;

            proxy_ssl_server_name on;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}