events {}

http {
    upstream backend_servers {
        # Default is round robin (no need to specify)

        server v-serve-backend.onrender.com:443 max_fails=2 fail_timeout=15s;
        server v-serve-hosting-2.onrender.com:443 max_fails=2 fail_timeout=15s;
        server volunteer-management-system-backend.onrender.com:443 max_fails=2 fail_timeout=15s;
    }

    server {
        listen 80;

        # prevent extra load
        location = /favicon.ico {
            return 204;
            access_log off;
            log_not_found off;
        }

        location / {
            proxy_pass https://backend_servers;

            #  REQUIRED for HTTPS upstream
            proxy_ssl_server_name on;

            # IMPORTANT FIX
            proxy_set_header Host $proxy_host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            # Failover (if server down → next one)
            proxy_next_upstream error timeout http_502 http_503 http_504;
            proxy_next_upstream_tries 2;

            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}